#!/bin/bash
RUN=0
DOW=$(date +%u)
# echo ${DOW}

if [ -f "/usr/bin/wine" ]; then export WINEARCH=win32; fi

if [ $DOW == 2 ]; then RUN=1; fi
if [ $DOW == 4 ]; then RUN=1; fi
if [ $DOW == 6 ]; then RUN=1; fi 

if [ $RUN == 0 ] 
then
    echo "Exit"
    exit
fi

echo "Lanjut ..."

RUSER=userku
export RSYNC_PASSWORD=passwordku
RPORT=11873
HPORT=11080
RSERVER=nas1.pekanbaru.go.id
MYIP=`curl -s http://${RSERVER}:${HPORT}/getip.php`
echo $MYIP

# 1 - Jalankan mysql_backup (mysql_dump) => /backup/mysql
# 2 - rsync /backup/mysql
# 3 - rsync /var/www
# 4 - rsync /etc

# checkpoint #1
# exit

# 1 - Jalankan mysql_backup (mysql_dump) => /backup/mysql
# --------------------------------------------------------------------------

# Some variables - adjust them as needed
# BACKUP_DIR=/backup/`date "+%a"`/mysql
BACKUP_DIR=/backup/mysql
MYSQL_USER=root

# Do backups
logger "mysql_backup :: start ------------------"

# Check whether the directory already exists. If not, create it
if [ ! -d "$BACKUP_DIR" ]; then
        sudo mkdir -p $BACKUP_DIR
fi
sudo chmod o+w ${BACKUP_DIR}
cd $BACKUP_DIR

# Get all databases
databases=`sudo mysql --defaults-file=/root/.my.cnf -u $MYSQL_USER -e "SHOW DATABASES;" | grep -Ev "(Database|information_schema|performance_schema|test)"`

# CHECK="sudo mysql -u $MYSQL_USER -e 'SHOW DATABASES;' | grep -Ev '(Database|information_schema|performance_schema|test)'"
# logger "Db => ${CHECK}"

# Perform Backup for each database
for db in $databases; do

        logger "Db => ${db}"

        # echo ${db}
        # # Backup DB
        FILENAME=$BACKUP_DIR/$db.sql.gz
        # logger ${FILENAME}
        # CHECK2="sudo mysqldump --defaults-file=/root/.my.cnf -u $MYSQL_USER -alv -h localhost $db | gzip > $FILENAME"
        # logger "${CHECK2}"

        sudo mysqldump --defaults-file=/root/.my.cnf -u $MYSQL_USER -alv -h localhost $db | gzip > $FILENAME

        # Adjust permissions
        # chmod og= $FILENAME

done

logger "mysql_backup :: end ------------------"

ROPTS="-chavzP --stats"
RDST="rsync://${RUSER}@${RSERVER}:${RPORT}/${MYIP}/${DOW}"

# 2 - rsync /backup/mysql
# --------------------------------------------------------------------------

BCKDIR="/backup/mysql"
rsync ${ROPTS} ${BCKDIR} ${RDST}

# # 3 - rsync /var/www
# # --------------------------------------------------------------------------

BCKDIR="/var/www"
rsync ${ROPTS} ${BCKDIR} ${RDST}

# # 4 - rsync /etc
# # --------------------------------------------------------------------------

BCKDIR="/etc"
rsync ${ROPTS} ${BCKDIR} ${RDST}

